# -*- coding: utf-8 -*-
from odoo import models, fields, api

class RuntimeEvent(models.Model):
    _name = 'nexora.runtime_event'
    _description = 'Runtime Lifecycle Event Timeline'
    _order = 'timestamp desc, id desc'

    generation_job_id = fields.Many2one('nexora.generation_job', string='Generation Job', ondelete='cascade', index=True)
    builder_session_id = fields.Many2one('nexora.builder_session', string='Builder Session', required=False, ondelete='cascade', index=True)
    runtime_id = fields.Many2one('nexora.runtime', string='Runtime', required=False, ondelete='set null')
    runtime_type = fields.Char(string='Runtime Type', required=True)
    event_type = fields.Selection([
          ('builder.planning.started', 'Builder Planning Started'),
          ('builder.planning.completed', 'Builder Planning Completed'),
          ('workspace.diff.generated', 'Workspace Diff Generated'),
          ('validation.started', 'Validation Started'),
          ('validation.completed', 'Validation Completed'),
          ('preview.generated', 'Preview Generated'),
          ('approval.requested', 'Approval Requested'),
          ('approval.granted', 'Approval Granted'),
          ('approval.rejected', 'Approval Rejected'),
          ('rollback.started', 'Rollback Started'),
          ('rollback.completed', 'Rollback Completed'),
          ('version.committed', 'Version Committed'),
          ('version.restored', 'Version Restored'),
        ('cache.rebuilt', 'Cache Rebuilt'),
        ('cache.invalidated', 'Cache Invalidated'),
        ('dependency.graph.updated', 'Dependency Graph Updated'),
        ('dependency.cycle_detected', 'Dependency Cycle Detected'),
        ('plugin.discovered', 'Plugin Discovered'),
        ('plugin.validated', 'Plugin Validated'),
        ('plugin.installed', 'Plugin Installed'),
        ('plugin.enabled', 'Plugin Enabled'),
        ('plugin.degraded', 'Plugin Degraded'),
        ('plugin.disabled', 'Plugin Disabled'),
        ('plugin.removed', 'Plugin Removed'),
        ('plugin.reloaded', 'Plugin Reloaded'),
        ('plugin.integrity_failed', 'Plugin Integrity Failed'),
        ('plugin.invalid_manifest', 'Plugin Invalid Manifest'),
        ('plugin.validation_failed', 'Plugin Validation Failed'),
        ('plugin.compatibility_failed', 'Plugin Compatibility Failed'),
        ('capability.discovered', 'Capability Discovered'),
        ('capability.validated', 'Capability Validated'),
        ('capability.installed', 'Capability Installed'),
        ('capability.enabled', 'Capability Enabled'),
        ('capability.degraded', 'Capability Degraded'),
        ('capability.disabled', 'Capability Disabled'),
        ('capability.upgraded', 'Capability Upgraded'),
        ('capability.downgraded', 'Capability Downgraded'),
        ('capability.removed', 'Capability Removed'),
        ('capability.cached', 'Capability Cached'),
        ('capability.validation_failed', 'Capability Validation Failed'),
        ('capability.conflict_detected', 'Capability Conflict Detected'),
        ('capability.loaded', 'Capability Loaded'),
        ('capability.unloaded', 'Capability Unloaded'),
        ('generation.started', 'Generation Started'),
        ('generation.completed', 'Generation Completed'),
        ('generation.failed', 'Generation Failed'),
        ('generation.stage.started', 'Generation Stage Started'),
        ('generation.stage.completed', 'Generation Stage Completed'),
        ('generation.stage.failed', 'Generation Stage Failed'),
        ('generation.rollback.started', 'Generation Rollback Started'),
        ('generation.rollback.completed', 'Generation Rollback Completed'),
        ('generation.rolled_back', 'Generation Rolled Back'),
        ('generation.rollback_failed', 'Generation Rollback Failed'),
        ('generation.provider.selected', 'Generation Provider Selected'),
        ('generation.ai.started', 'Generation Ai Started'),
        ('generation.ai.completed', 'Generation Ai Completed'),
        ('generation.diff.completed', 'Generation Diff Completed'),
        ('generation.validation.completed', 'Generation Validation Completed'),
        ('generation.resume.started', 'Generation Resume Started'),
        ('generation.resume.completed', 'Generation Resume Completed'),
        ('generation.artifact.generated', 'Generation Artifact Generated'),
        ('generation.runtime.ready', 'Generation Runtime Ready'),
        ('generation.builder_session_created', 'Generation Builder Session Created'),
        ('generation.runtimes_started', 'Generation Runtimes Started'),
        ('generation.git_initialized', 'Generation Git Initialized'),
        ('generation.warning', 'Generation Warning'),
        ('workspace.created', 'Workspace Created'),
        ('workspace.opened', 'Workspace Opened'),
        ('workspace.archived', 'Workspace Archived'),
        ('workspace.cloned', 'Workspace Cloned'),
        ('workspace.restored', 'Workspace Restored'),
        ('workspace.cleaned', 'Workspace Cleaned'),
        ('workspace.deleted', 'Workspace Deleted'),
        ('file.opened', 'File Opened'),
        ('file.saved', 'File Saved'),
        ('file.created', 'File Created'),
        ('file.deleted', 'File Deleted'),
        ('file.renamed', 'File Renamed'),
        ('file.moved', 'File Moved'),
        ('file.write_failed', 'File Write Failed'),
        ('file.conflict', 'File Conflict'),
        ('folder.created', 'Folder Created'),
        ('folder.deleted', 'Folder Deleted'),
        ('folder.renamed', 'Folder Renamed'),
        ('folder.moved', 'Folder Moved'),
        ('runtime.started', 'Runtime Started'),
        ('runtime.stopped', 'Runtime Stopped'),
        ('runtime.restarted', 'Runtime Restarted'),
        ('runtime.crashed', 'Runtime Crashed'),
        ('runtime.recovered', 'Runtime Recovered'),
        ('runtime.health_check', 'Runtime Health Check'),
        ('preview.started', 'Preview Started'),
        ('preview.stopped', 'Preview Stopped'),
        ('preview.ready', 'Preview Ready'),
        ('preview.crashed', 'Preview Crashed'),
        ('git.initialized', 'Git Initialized'),
        ('git.committed', 'Git Committed'),
        ('git.checkpoint.created', 'Git Checkpoint Created'),
        ('git.rollback', 'Git Rollback'),
        ('git.checkpoint.restored', 'Git Checkpoint Restored'),
        ('git.repository.initialized', 'Git Repository Initialized'),
        ('git.commit.created', 'Git Commit Created'),
        ('git.branch.created', 'Git Branch Created'),
        ('git.branch.deleted', 'Git Branch Deleted'),
        ('git.checkout.completed', 'Git Checkout Completed'),
        ('git.restore.completed', 'Git Restore Completed'),
        ('git.commit.failed', 'Git Commit Failed'),
        ('git.push.completed', 'Git Push Completed'),
        ('git.pull.completed', 'Git Pull Completed'),
        ('git.merge.started', 'Git Merge Started'),
        ('git.merge.completed', 'Git Merge Completed'),
        ('git.merge.conflict', 'Git Merge Conflict'),
        ('git.rebase.started', 'Git Rebase Started'),
        ('git.rebase.completed', 'Git Rebase Completed'),
        ('git.rebase.failed', 'Git Rebase Failed'),
        ('git.fetch.completed', 'Git Fetch Completed'),
        ('git.status.updated', 'Git Status Updated'),
        ('ai.review.started', 'Ai Review Started'),
        ('ai.review.completed', 'Ai Review Completed'),
        ('ai.intent.detected', 'Ai Intent Detected'),
        ('ai.plan.created', 'Ai Plan Created'),
        ('ai.capabilities.selected', 'Ai Capabilities Selected'),
        ('ai.tools.selected', 'Ai Tools Selected'),
        ('ai.context.collected', 'Ai Context Collected'),
        ('ai.execution.started', 'Ai Execution Started'),
        ('ai.patch.generated', 'Ai Patch Generated'),
        ('ai.patch.rejected', 'Ai Patch Rejected'),
        ('ai.execution.completed', 'Ai Execution Completed'),
        ('ai.execution.failed', 'Ai Execution Failed'),
        
        ('planner.started', 'Planner Started'),
        ('requirements.analyzed', 'Requirements Analyzed'),
        ('blueprint.generated', 'Blueprint Generated'),
        ('capabilities.selected', 'Capabilities Selected'),
        ('execution.plan.created', 'Execution Plan Created'),
        ('planner.completed', 'Planner Completed'),
        ('planner.failed', 'Planner Failed'),

        ('generation.started', 'Generation Engine Started'),
        ('stage.started', 'Stage Started'),
        ('task.started', 'Task Started'),
        ('task.generated', 'Task Generated'),
        ('task.validated', 'Task Validated'),
        ('task.failed', 'Task Failed'),
        ('task.retry', 'Task Retry'),
        ('task.completed', 'Task Completed'),
        ('stage.completed', 'Stage Completed'),
        ('preview.updated', 'Preview Updated'),
        ('generation.completed', 'Generation Engine Completed'),
        ('generation.failed', 'Generation Engine Failed'),

        ('deployment.started', 'Deployment Started'),
        ('deployment.completed', 'Deployment Completed'),
        ('deployment.failed', 'Deployment Failed'),
        ('session.state_changed', 'Session State Changed'),
        ('session.error', 'Session Error'),
        ('session.created', 'Session Created'),
        ('session.destroyed', 'Session Destroyed'),
        ('mcp.started', 'Mcp Started'),
        ('mcp.ready', 'Mcp Ready'),
        ('mcp.stopped', 'Mcp Stopped'),
        ('mcp.recovered', 'Mcp Recovered'),
        ('mcp.connected', 'Mcp Connected'),
        ('mcp.disconnected', 'Mcp Disconnected'),
        ('mcp.tool.executed', 'Mcp Tool Executed'),
        ('mcp.tool.failed', 'Mcp Tool Failed'),
        ('mcp.client.connected', 'Mcp Client Connected'),
        ('mcp.client.disconnected', 'Mcp Client Disconnected'),
        ('mcp.warning', 'Mcp Warning'),
        ('mcp.error', 'Mcp Error'),
        ('tool.started', 'Tool Started'),
        ('tool.completed', 'Tool Completed'),
        ('tool.failed', 'Tool Failed'),
        ('tool.warning', 'Tool Warning'),
        ('tool.rollback', 'Tool Rollback'),
        ('STARTING', 'Starting'),
        ('STARTED', 'Started'),
        ('HEALTHY', 'Healthy'),
        ('DEGRADED', 'Degraded'),
        ('STOPPING', 'Stopping'),
        ('STOPPED', 'Stopped'),
        ('FAILED', 'Failed'),
        ('RECOVERED', 'Recovered'),
        ('ATTACHED', 'Attached'),
        ('DETACHED', 'Detached'),
    ], string='Event Type', required=True, index=True)
    timestamp = fields.Datetime(string='Timestamp', default=fields.Datetime.now, required=True)
    message = fields.Text(string='Message')
