"""
Standardized machine-readable error codes for authentication APIs.
React must rely on these codes for UI behavior, not message strings.
"""

# Authentication
AUTH_INVALID_CREDENTIALS = "AUTH_001"
AUTH_ACCOUNT_LOCKED = "AUTH_002"
AUTH_SESSION_INVALID = "AUTH_003"
AUTH_SESSION_FORCED_LOGOUT = "AUTH_004"
AUTH_UNAUTHORIZED = "AUTH_005"
AUTH_PASSWORD_CHANGE_FAILED = "AUTH_006"
AUTH_PASSWORD_RESET_FAILED = "AUTH_007"

# Authorization
AUTHZ_FORBIDDEN = "AUTHZ_001"
AUTHZ_INSUFFICIENT_ROLE = "AUTHZ_002"

# User Management
USER_NOT_FOUND = "USER_001"
USER_CREATE_FAILED = "USER_002"
USER_UPDATE_FAILED = "USER_003"
USER_DELETE_FAILED = "USER_004"
USER_ALREADY_EXISTS = "USER_005"

# Session Management
SESSION_NOT_FOUND = "SESSION_001"
SESSION_FORCE_LOGOUT_FAILED = "SESSION_002"

# Audit
AUDIT_FETCH_FAILED = "AUDIT_001"

# Generic
INTERNAL_ERROR = "SYS_001"
VALIDATION_ERROR = "SYS_002"
NOT_FOUND = "SYS_003"
