# -*- coding: utf-8 -*-
"""Phase 45 U5 — generation integration: discovery publishes candidates on the
artifact bus; enrichment consumes them; placeholder fallback preserved."""
import unittest
from unittest.mock import patch, MagicMock

from odoo.addons.nexora_studio.services.generation.engines.component_discovery_engine import (
    ComponentDiscoveryEngine,
)
from odoo.addons.nexora_studio.services.generation.engines.component_intelligence_engine import (
    ComponentIntelligenceEngine,
)
from odoo.addons.nexora_studio.services.source_framework.domain_models import (
    ComponentPackage, Provenance,
)


class _Runtime:
    """Minimal runtime facade: exposes a truthy env only."""
    env = MagicMock()
    from unittest.mock import MagicMock as _MM
    orchestrator = type("_O", (), {})()
    orchestrator.env = _MM()


def _artifact_with(candidates):
    import dataclasses
    from odoo.addons.nexora_studio.services.generation.core.generation_context import (
        WebsiteGenerationArtifact,
    )
    art = WebsiteGenerationArtifact()
    art = art.evolve(architecture=dataclasses.replace(
        art.architecture,
        component_hierarchy={
            "page_home": {"type": "page", "sections": ["hero"]},
        }))
    art = art.evolve(generation_metadata={
        "modular_blueprint": {
            "component": {"abstract_components": [
                {"id": "hero_section", "purpose": "hero"},
                {"id": "footer_section", "purpose": "footer"},
            ]}
        }
    })
    if candidates is not None:
        art = art.evolve(generation_metadata={
            **art.generation_metadata,
            "candidate_components": candidates,
        })
    return art


def _pkg(name, description):
    return ComponentPackage(
        component_id="hero/HeroScene.tsx", name=name, description=description,
        metadata={"source_code": "/* real 3d hero */"},
        provenance=Provenance(provider="threed_component_library"),
    )


class TestGenerationIntegration(unittest.TestCase):

    def _run_pair(self, artifact):
        disc = ComponentDiscoveryEngine(None)
        intel = ComponentIntelligenceEngine(None)
        rt = _Runtime()

        # Discovery: SearchEngine returns our package -> published on artifact.
        with patch("odoo.addons.nexora_studio.services.source_framework."
                   "search_engine.SearchEngine") as SE:
            se = SE.return_value
            se.search.return_value = [
                {"package": p, "score": 0.9, "final_score": 0.8}
                for p in (artifact.generation_metadata.get("candidate_components") or [])
            ]
            r1 = disc.execute(artifact, rt)
        self.assertTrue(r1.success)

        # Intelligence consumes the artifact bus (not result.metadata).
        r2 = intel.execute(r1.artifact, rt)
        self.assertTrue(r2.success)
        return r1, r2

    def test_candidate_available_is_consumed(self):
        pkg = _pkg("Hero3D", "3d hero scene built with react-three-fiber")
        r1, r2 = self._run_pair(_artifact_with([pkg]))

        # Published on the artifact bus by discovery.
        self.assertEqual(
            len(r1.artifact.generation_metadata.get("candidate_components", [])), 1)

        nodes = r2.artifact.component_tree.nodes
        hero = [n for n in nodes if n["metadata"].get("semantic") == "hero"
                or n["component_id"] == "hero/HeroScene.tsx"]
        self.assertTrue(hero, "matched section must use the candidate")
        self.assertEqual(hero[0]["component_id"], "hero/HeroScene.tsx")
        self.assertEqual(hero[0]["code"], "/* real 3d hero */")
        self.assertTrue(hero[0]["metadata"].get("from_source"))

        footer = [n for n in nodes if n["metadata"].get("semantic") == "footer"]
        self.assertTrue(footer, "unmatched sections keep placeholder")
        self.assertEqual(footer[0]["code"], "/* Code generated by Orchestrator */")

    def test_candidate_unavailable_preserves_placeholder(self):
        r1, r2 = self._run_pair(_artifact_with([]))
        self.assertEqual(r1.artifact.generation_metadata.get("candidate_components"), [])
        nodes = r2.artifact.component_tree.nodes
        self.assertTrue(nodes)
        self.assertTrue(all(n["code"] == "/* Code generated by Orchestrator */"
                            for n in nodes))

    def test_discovery_publishes_on_artifact_bus_even_when_search_empty(self):
        r1, _ = self._run_pair(_artifact_with([]))
        self.assertIn("candidate_components", r1.artifact.generation_metadata)


if __name__ == '__main__':
    unittest.main()
