# -*- coding: utf-8 -*-
from odoo import models, api
import os

class ConfigStage(models.AbstractModel):
    _name = 'nexora.stage.config'
    _inherit = 'nexora.stage.base'
    _description = 'Configuration Stage'
    _stage_type = 'config'

    @api.model
    def execute(self, job, stage, context):
        self.env['nexora.variable_engine'].execute_stage_variables(stage, job)
        
        fs = self.env['nexora.filesystem_service']
        target = job.target_workspace_path
        
        # Write basic config files if they don't exist
        configs = {
            '.env.example': 'PROJECT_NAME={{PROJECT_NAME}}\nENV=development\n',
            '.gitignore': 'node_modules/\n__pycache__/\n.env\n',
            'README.md': '# {{PROJECT_NAME}}\nGenerated by Nexora Studio.\n',
            'docker-compose.yml': 'version: "3.8"\nservices:\n  app:\n    image: nginx\n',
            '.editorconfig': 'root = true\n\n[*]\nindent_style = space\nindent_size = 2\n'
        }
        
        for filename, template in configs.items():
            filepath = os.path.join(target, filename)
            if not fs.file_exists(filepath):
                fs.write_file(filepath, template)
                
        # Sub variables again on the new configs
        var_map = self.env['nexora.variable_engine'].resolve_job_variables(job)
        self.env['nexora.variable_engine'].process_directory(target, var_map)
        
        context.stage_data[str(stage.id)] = {'configs_generated': list(configs.keys())}
        return context

    @api.model
    def rollback(self, job, stage, context):
        fs = self.env['nexora.filesystem_service']
        data = context.stage_data.get(str(stage.id), {})
        for f in data.get('configs_generated', []):
            path = os.path.join(job.target_workspace_path, f)
            fs.remove_path(path)
