import logging
import os
from typing import Any
from odoo.addons.nexora_studio.services.generation.engines.base_engine import BaseGenerationEngine, EngineExecutionResult
from odoo.addons.nexora_studio.services.generation.core.generation_context import WebsiteGenerationArtifact

_logger = logging.getLogger(__name__)

class CodeGenerationEngine(BaseGenerationEngine):
    """
    Core AI Code Generation Engine supporting Iterative Generation -> Review -> Fix -> Approve workflow.
    """
    def execute(self, artifact: WebsiteGenerationArtifact, runtime: 'GenerationRuntime') -> EngineExecutionResult:
        _logger.info("Executing CodeGenerationEngine (Phase 21E.2 Iterative Engine)...")
        
        try:
            # We instantiate ReviewEngine locally to drive the qualitative feedback loops
            from odoo.addons.nexora_studio.services.generation.engines.review_engine import ReviewEngine
            review_engine = ReviewEngine(self.orchestrator)
            
            # Iterative Page-by-Page and Section-by-Section logic
            applied_count = 0
            tasks = []
            
            # Consume modular blueprint
            modular_blueprint_dict = artifact.generation_metadata.get("modular_blueprint", {})
            
            # Retrieve architecture hierarchy generated by ArchitectureEngine
            component_hierarchy = artifact.architecture.component_hierarchy if hasattr(artifact.architecture, "component_hierarchy") else {}
            
            for comp_id, comp_data in component_hierarchy.items():
                if comp_data.get("type") != "page": continue
                
                path = comp_data.get("path", "/")
                filename = "index.tsx" if path == "/" else f"{path.strip('/')}.tsx"
                page_path = f"src/pages/{filename}"
                page_code = ""
                
                # Retrieve sections mapped for this page
                sections = comp_data.get("sections", ["Hero", "Content"])
                
                for section in sections:
                    # 1. Generate Section
                    section_code = self._generate_section(section, artifact, runtime, modular_blueprint_dict)
                    
                    # 2. Review Section & Fix Loop
                    max_fixes = 3
                    for i in range(max_fixes):
                        issues = review_engine.review_section(section, section_code, runtime)
                        if not issues:
                            break # Approve Section
                        _logger.info(f"Fixing {len(issues)} issues in section {section} (Attempt {i+1})")
                        section_code = self._fix_code(section_code, issues, runtime)
                        
                    page_code += f"\n{section_code}\n"
                
                # 3. Page Review & Fix Loop
                max_fixes = 3
                for i in range(max_fixes):
                    issues = review_engine.review_page(path, page_code, runtime)
                    if not issues:
                        break # Approve Page
                    _logger.info(f"Fixing {len(issues)} issues on page {path} (Attempt {i+1})")
                    page_code = self._fix_code(page_code, issues, runtime)
                    
                # 4. Apply Page Code
                self._apply_patch(page_path, page_code, runtime)
                applied_count += 1
                tasks.append(page_path)
            
            metadata = {
                "tasks_planned": len(tasks),
                "patches_applied": applied_count
            }
            return EngineExecutionResult(success=True, artifact=artifact, metadata=metadata, error=None)
            
        except Exception as e:
            _logger.error(f"CodeGenerationEngine failed: {e}", exc_info=True)
            return EngineExecutionResult(success=False, artifact=artifact, metadata={}, error=str(e))
            
    def _generate_section(self, section: str, artifact: WebsiteGenerationArtifact, runtime: 'GenerationRuntime', modular_blueprint_dict: dict) -> str:
        payload = {
            "task": f"Generate React component for {section}",
            "theme": artifact.theme.__dict__ if hasattr(artifact.theme, '__dict__') else {},
            "blueprint": modular_blueprint_dict
        }
        try:
            response = runtime.ai.generate("ai_code_patch", payload)
            return response.get("full_content", f"// Generated section {section}")
        except Exception as e:
            _logger.warning(f"Failed to generate section {section}: {e}")
            return f"// Failed to generate {section}"
            
    def _fix_code(self, code: str, issues: list, runtime: 'GenerationRuntime') -> str:
        payload = {
            "task": "Fix the provided code based on review issues",
            "code": code,
            "issues": issues
        }
        try:
            response = runtime.ai.generate("ai_bug_fixing", payload)
            return response.get("full_content", code)
        except Exception as e:
            _logger.warning(f"Failed to fix code: {e}")
            return code
            
    def _apply_patch(self, path: str, code: str, runtime: 'GenerationRuntime') -> None:
        try:
            runtime.workspace.write_file(path, code)
        except Exception as e:
            _logger.error(f"Failed to apply patch to {path}: {e}")
