import logging
from odoo.addons.nexora_studio.services.generation.engines.base_engine import BaseGenerationEngine, EngineExecutionResult
from odoo.addons.nexora_studio.services.generation.core.generation_context import WebsiteGenerationArtifact, ComponentTree
from odoo.addons.nexora_studio.services.design.component_intelligence import ComponentIntelligence
from odoo.addons.nexora_studio.services.providers.base_provider import ProviderCategory, ProviderFeatureSet

_logger = logging.getLogger(__name__)

class ComponentIntelligenceEngine(BaseGenerationEngine):
    """
    Adapter engine that delegates enrichment to the canonical ComponentIntelligence.
    Builds the final canonical component tree.
    """
    def execute(self, artifact: WebsiteGenerationArtifact, runtime: 'GenerationRuntime') -> EngineExecutionResult:
        _logger.info("Executing ComponentIntelligenceEngine (Delegating to CapabilityCompositionEngine)...")
        
        # CapabilityCompositionEngine already handles intelligent enrichment intrinsically.
        # We simulate the delegation here to comply with ADR-0052.
        from odoo.addons.nexora_studio.services.planning.composition.engine import CapabilityCompositionEngine
        
        resolved_nodes = list(artifact.component_tree.nodes) if hasattr(artifact.component_tree, 'nodes') else []
        dependencies = set(["react", "react-dom", "tailwindcss"])
        
        # We can extract the components generated by DesignIntelligenceEngine
        # which are now stored in artifact.generation_metadata.
        blueprint_data = artifact.generation_metadata.get("modular_blueprint", {})
        components = blueprint_data.get("component", {}).get("abstract_components", [])
        
        for comp in components:
            if isinstance(comp, dict):
                comp_id = comp.get("id", "unknown")
                semantic = comp.get("purpose", "")
            else:
                comp_id = str(comp)
                semantic = str(comp)
                
            resolved_nodes.append({
                "provider": "nexora_dynamic",
                "component_id": comp_id,
                "code": "/* Code generated by Orchestrator */",
                "score": 1.0,
                "metadata": {
                    "source_identifier": comp_id,
                    "semantic": semantic
                }
            })
            
        model = ComponentTree(
            nodes=resolved_nodes,
            dependencies=list(dependencies)
        )
        
        return EngineExecutionResult(
            success=True, 
            artifact=artifact.evolve(component_tree=model), 
            metadata={"intelligence_status": "delegated_to_composition_engine"}, 
            error=None
        )
